address: https://exnihiloexhibition.com
submissions_email: exnihilo.submissions@gmail.com
contact_email: exnihilo.exhibition@gmail.com
facebook_link: https://facebook.com/whatever
instagram_link: https://www.instagram.com/art_ex_nihilo/
