address: https://exnihiloexhibition.com
submissions_email: exnihilo.submissions@gmail.com
contact_email: exnihilo.exhibition@gmail.com
facebook_link: https://www.facebook.com/Ex-Nihilo-113483780439979
instagram_link: https://www.instagram.com/art_ex_nihilo/
#permalink: slug

plugins:
  - jekyll-datapage-generator

page_gen-dirs: false
page_gen:
  - data: artists
    template: artist_page
    dir: a
    name_expr: record['name'].downcase.gsub(" ", "_")
    title_expr: record['name'] + ' - EX NIHILO'
    page_data_prefix: artist
  - data: artworks
    template: artwork_page
    dir: w
    name_expr: record['title'].downcase.gsub(" ", "_")
    title_expr: record['title'] + ' - EX NIHILO'
    page_data_prefix: artwork
